-- Referência da migration inicial. O runtime aplica a mesma estrutura de forma
-- idempotente em src/server/tradingRepository.ts e registra schema_migrations.
CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY, applied_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS live_sessions (id TEXT PRIMARY KEY, asset TEXT NOT NULL, strategy_version TEXT NOT NULL, started_at INTEGER NOT NULL, ended_at INTEGER, status TEXT NOT NULL, payload_json TEXT NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS trading_sessions (id TEXT PRIMARY KEY, source TEXT NOT NULL, symbol TEXT NOT NULL, trading_date TEXT, timeframe TEXT NOT NULL, started_at INTEGER NOT NULL, ended_at INTEGER, technique_version TEXT, segment_count INTEGER NOT NULL DEFAULT 0, event_count INTEGER NOT NULL DEFAULT 0, trade_count INTEGER NOT NULL DEFAULT 0, payload_json TEXT NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS segments (id TEXT PRIMARY KEY, session_id TEXT, started_at INTEGER NOT NULL, ended_at INTEGER, reason TEXT, trading_date TEXT, payload_json TEXT NOT NULL, created_at INTEGER NOT NULL, FOREIGN KEY(session_id) REFERENCES trading_sessions(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS market_events (id TEXT PRIMARY KEY, session_id TEXT, segment_id TEXT, timestamp INTEGER NOT NULL, market_time TEXT, type TEXT NOT NULL, direction TEXT, price REAL, source TEXT, model_version TEXT, technique_version TEXT, payload_json TEXT NOT NULL, created_at INTEGER NOT NULL, FOREIGN KEY(session_id) REFERENCES trading_sessions(id) ON DELETE SET NULL, FOREIGN KEY(segment_id) REFERENCES segments(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS backtest_runs (id TEXT PRIMARY KEY, strategy_version TEXT NOT NULL, asset TEXT NOT NULL, timeframe TEXT NOT NULL, source_capture_id TEXT NOT NULL, origin TEXT NOT NULL, created_at INTEGER NOT NULL, payload_json TEXT NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS trades (id TEXT PRIMARY KEY, backtest_id TEXT, session_id TEXT, segment_id TEXT, origin TEXT NOT NULL, symbol TEXT NOT NULL, trading_date TEXT, timeframe TEXT NOT NULL, direction TEXT NOT NULL, setup TEXT NOT NULL, strategy_version TEXT NOT NULL, opened_at INTEGER NOT NULL, closed_at INTEGER NOT NULL, result_r REAL NOT NULL, payload_json TEXT NOT NULL, created_at INTEGER NOT NULL, FOREIGN KEY(backtest_id) REFERENCES backtest_runs(id) ON DELETE CASCADE, FOREIGN KEY(session_id) REFERENCES trading_sessions(id) ON DELETE SET NULL, FOREIGN KEY(segment_id) REFERENCES segments(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS replay_sessions (session_id TEXT PRIMARY KEY, created_at INTEGER NOT NULL, symbol TEXT NOT NULL, timeframe TEXT NOT NULL, strategy_version TEXT NOT NULL, payload_json TEXT NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS techniques (version TEXT PRIMARY KEY, status TEXT NOT NULL CHECK(status IN ('PRODUCTION','ARCHIVED')), rules_json TEXT NOT NULL, created_at INTEGER NOT NULL, promoted_at INTEGER);
CREATE TABLE IF NOT EXISTS technique_candidates (id TEXT PRIMARY KEY, version TEXT NOT NULL, base_version TEXT NOT NULL, hypothesis TEXT NOT NULL, status TEXT NOT NULL, rules_json TEXT NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS validation_results (id TEXT PRIMARY KEY, candidate_id TEXT, kind TEXT NOT NULL, status TEXT NOT NULL, metrics_json TEXT NOT NULL, created_at INTEGER NOT NULL, FOREIGN KEY(candidate_id) REFERENCES technique_candidates(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS app_state (key TEXT PRIMARY KEY, payload_json TEXT NOT NULL, updated_at INTEGER NOT NULL);
